package IMC.telas;

import IMC.model.GastoCalorico;
import javax.swing.JOptionPane;

public class TelaGastoCalorico extends javax.swing.JFrame {

    /**
     * Creates new form TelaGastoCalorico
     */
    public TelaGastoCalorico() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        OptionHomem = new javax.swing.JRadioButton();
        OptionMulher = new javax.swing.JRadioButton();
        titlePeso = new javax.swing.JLabel();
        titleAltura = new javax.swing.JLabel();
        titleIdade = new javax.swing.JLabel();
        titleAtividades = new javax.swing.JLabel();
        TxPesoCal = new javax.swing.JTextField();
        TxAlturaCal = new javax.swing.JTextField();
        TxIdadeCal = new javax.swing.JTextField();
        MenuAtividade = new javax.swing.JComboBox<>();
        botaoCalcular = new javax.swing.JButton();
        titlePag = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titleGastoBasal = new javax.swing.JLabel();
        titleGastoTotal = new javax.swing.JLabel();
        gastoBasal = new javax.swing.JLabel();
        gastoTotal = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gasto Calórico");

        jPanel3.setBackground(new java.awt.Color(42, 36, 36));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        OptionHomem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OptionHomem.setForeground(new java.awt.Color(255, 255, 255));
        OptionHomem.setText("Homen");

        OptionMulher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OptionMulher.setForeground(new java.awt.Color(255, 255, 255));
        OptionMulher.setText("Mulher");
        OptionMulher.setToolTipText("");
        OptionMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionMulherActionPerformed(evt);
            }
        });

        titlePeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titlePeso.setForeground(new java.awt.Color(255, 255, 255));
        titlePeso.setText("Peso (Kg): ");

        titleAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleAltura.setForeground(new java.awt.Color(255, 255, 255));
        titleAltura.setText("Altura (Cm): ");

        titleIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleIdade.setForeground(new java.awt.Color(255, 255, 255));
        titleIdade.setText("Idade: ");

        titleAtividades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleAtividades.setForeground(new java.awt.Color(255, 255, 255));
        titleAtividades.setText("Nível de atividade:");

        TxPesoCal.setBackground(new java.awt.Color(204, 204, 204));
        TxPesoCal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxPesoCal.setForeground(new java.awt.Color(0, 0, 0));

        TxAlturaCal.setBackground(new java.awt.Color(204, 204, 204));
        TxAlturaCal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxAlturaCal.setForeground(new java.awt.Color(0, 0, 0));

        TxIdadeCal.setBackground(new java.awt.Color(204, 204, 204));
        TxIdadeCal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxIdadeCal.setForeground(new java.awt.Color(0, 0, 0));

        MenuAtividade.setBackground(new java.awt.Color(204, 204, 204));
        MenuAtividade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuAtividade.setForeground(new java.awt.Color(0, 0, 0));
        MenuAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentário", "Leve (exercício leve 1 a 3 dias/semana)", "Moderado (exercício moderado 3 a 5 dias/semana)", "Ativo (exercício pesado 5 a 6 dias/semana)", "Extremamente ativo (exercício pesado diário)" }));
        MenuAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAtividadeActionPerformed(evt);
            }
        });

        botaoCalcular.setBackground(new java.awt.Color(255, 51, 0));
        botaoCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCalcular.setForeground(new java.awt.Color(255, 255, 255));
        botaoCalcular.setText("Calcular");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OptionMulher)
                        .addGap(32, 32, 32)
                        .addComponent(OptionHomem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleAtividades)
                            .addComponent(titleIdade)
                            .addComponent(titleAltura)
                            .addComponent(titlePeso))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuAtividade, 0, 420, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxPesoCal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxAlturaCal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxIdadeCal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptionHomem)
                    .addComponent(OptionMulher))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePeso)
                    .addComponent(TxPesoCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleAltura)
                    .addComponent(TxAlturaCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleIdade)
                    .addComponent(TxIdadeCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleAtividades)
                    .addComponent(MenuAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        titlePag.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titlePag.setForeground(new java.awt.Color(255, 255, 255));
        titlePag.setText("Cálculo de GastoCalorico");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleGastoBasal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleGastoBasal.setForeground(new java.awt.Color(255, 255, 255));
        titleGastoBasal.setText("Gasto Basal: ");

        titleGastoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleGastoTotal.setForeground(new java.awt.Color(255, 255, 255));
        titleGastoTotal.setText("Gasto Total:");

        gastoBasal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gastoBasal.setForeground(new java.awt.Color(51, 255, 51));

        gastoTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gastoTotal.setForeground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleGastoTotal)
                    .addComponent(titleGastoBasal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(gastoBasal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(gastoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleGastoBasal)
                    .addComponent(gastoBasal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleGastoTotal)
                    .addComponent(gastoTotal))
                .addGap(24, 24, 24))
        );

        botaoVoltar.setBackground(new java.awt.Color(255, 153, 0));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(titlePag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePag)
                    .addComponent(botaoVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OptionMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionMulherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionMulherActionPerformed

    private void MenuAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAtividadeActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        GastoCalorico cal = new GastoCalorico();

        double calBasal = 0;
        double calTotal = 0;
        String GastoBasal, GastoTotal;

        if (TxAlturaCal.getText().isBlank() || TxIdadeCal.getText().isBlank()
                || TxPesoCal.getText().isBlank() || TxAlturaCal.getText().isEmpty() || TxIdadeCal.getText().isEmpty()
                || TxPesoCal.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Informe os campos corretamente!\nExemplo:\nPeso: 84\nAltura:184\nIdade: 26", "INFORMATIVO", 1);
        } else {

            try {

                String strPesoCal = TxPesoCal.getText();
                cal.setPesoCal(Double.parseDouble(strPesoCal));

                String strAlturaCal = TxAlturaCal.getText();
                cal.setAlturaCal(Integer.parseInt(strAlturaCal));

                String strIdadeCal = TxIdadeCal.getText();
                cal.setIdadeCal(Integer.parseInt(strIdadeCal));

                if (cal.getAlturaCal() == 0 || cal.getIdadeCal() == 0 || cal.getPesoCal() == 0) {
                    throw new ArithmeticException("Informe um valor maior que zero!");
                }

                if (OptionHomem.isSelected()) {
                    calBasal = 66 + (13.8 * cal.getPesoCal()) + (5 * cal.getAlturaCal()) - (6.8 * cal.getIdadeCal());

                    String strCalBasal = String.format("%.2f", calBasal);

                    switch (MenuAtividade.getSelectedItem().toString()) {
                        case "Sedentário":
                            calTotal = calBasal * 1.2;
                            break;
                        case "Leve (exercício leve 1 a 3 dias/semana)":
                            calTotal = calBasal * 1.375;
                            break;
                        case "Moderado (exercício moderado 3 a 5 dias/semana)":
                            calTotal = calBasal * 1.55;
                            break;
                        case "Ativo (exercício pesado 5 a 6 dias/semana)":
                            calTotal = calBasal * 1.725;
                            break;
                        case "Extremamente ativo (exercício pesado diário)":
                            calTotal = calBasal * 1.9;
                            break;
                    }
                } else if (OptionMulher.isSelected()) {
                    calBasal = 655 + (9.6 * cal.getPesoCal()) + (1.9 * cal.getAlturaCal()) - (4.7 * cal.getIdadeCal());

                    String strCalBasal = String.format("%.2f", calBasal);

                    switch (MenuAtividade.getSelectedItem().toString()) {
                        case "Sedentário":
                            calTotal = calBasal * 1.2;
                            break;
                        case "Leve (exercício leve 1 a 3 dias/semana)":
                            calTotal = calBasal * 1.375;
                            break;
                        case "Moderado (exercício moderado 3 a 5 dias/semana)":
                            calTotal = calBasal * 1.55;
                            break;
                        case "Ativo (exercício pesado 5 a 6 dias/semana)":
                            calTotal = calBasal * 1.725;
                            break;
                        case "Extremamente ativo (exercício pesado diário)":
                            calTotal = calBasal * 1.9;
                            break;
                    }
                }

                String strGastoBasal = String.format("%.2f", calBasal);
                String strCalTotal = String.format("%.2f", calTotal);

                gastoBasal.setText(strGastoBasal);
                gastoTotal.setText(strCalTotal);

            } catch (ArithmeticException e) {
                JOptionPane.showMessageDialog(null, "Informe um valor maior que zero!", "ATENÇÃO", 2);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Informações inválidas!\nInforme apenas números", "ATENÇÃO", 2);
            }
        }
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGastoCalorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MenuAtividade;
    private javax.swing.JRadioButton OptionHomem;
    private javax.swing.JRadioButton OptionMulher;
    private javax.swing.JTextField TxAlturaCal;
    private javax.swing.JTextField TxIdadeCal;
    private javax.swing.JTextField TxPesoCal;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel gastoBasal;
    private javax.swing.JLabel gastoTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel titleAltura;
    private javax.swing.JLabel titleAtividades;
    private javax.swing.JLabel titleGastoBasal;
    private javax.swing.JLabel titleGastoTotal;
    private javax.swing.JLabel titleIdade;
    private javax.swing.JLabel titlePag;
    private javax.swing.JLabel titlePeso;
    // End of variables declaration//GEN-END:variables
}
