package IMC.telas;

import IMC.model.Recomendacao;
import javax.swing.JOptionPane;

public class TelaRecomendacao extends javax.swing.JFrame {

    public TelaRecomendacao() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxCaloriasDiarias = new javax.swing.JTextField();
        botaoCalcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titleCarboidratos = new javax.swing.JLabel();
        titleProteinas = new javax.swing.JLabel();
        titleGorduras = new javax.swing.JLabel();
        resultadoCarboidrato = new javax.swing.JLabel();
        resultadoProteina = new javax.swing.JLabel();
        resultadoGorduras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recomendação");
        setBackground(new java.awt.Color(42, 36, 36));

        jPanel3.setBackground(new java.awt.Color(42, 36, 36));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recomendação");

        botaoVoltar.setBackground(new java.awt.Color(255, 153, 0));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calorias diárias (kcal):");

        TxCaloriasDiarias.setBackground(new java.awt.Color(204, 204, 204));
        TxCaloriasDiarias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxCaloriasDiarias.setForeground(new java.awt.Color(0, 0, 0));
        TxCaloriasDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCaloriasDiariasActionPerformed(evt);
            }
        });

        botaoCalcular.setBackground(new java.awt.Color(255, 51, 0));
        botaoCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCalcular.setForeground(new java.awt.Color(255, 255, 255));
        botaoCalcular.setText("Calcular");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxCaloriasDiarias, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxCaloriasDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botaoCalcular)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleCarboidratos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleCarboidratos.setForeground(new java.awt.Color(255, 255, 255));
        titleCarboidratos.setText("Carboidratos (50%):");

        titleProteinas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleProteinas.setForeground(new java.awt.Color(255, 255, 255));
        titleProteinas.setText("Proteínas (25%):");

        titleGorduras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleGorduras.setForeground(new java.awt.Color(255, 255, 255));
        titleGorduras.setText("Gorduras (25%):");

        resultadoCarboidrato.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resultadoCarboidrato.setForeground(new java.awt.Color(0, 153, 0));

        resultadoProteina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resultadoProteina.setForeground(new java.awt.Color(0, 153, 0));

        resultadoGorduras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resultadoGorduras.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(titleCarboidratos)
                        .addGap(18, 18, 18)
                        .addComponent(resultadoCarboidrato))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(titleProteinas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultadoProteina))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(titleGorduras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultadoGorduras)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleCarboidratos)
                    .addComponent(resultadoCarboidrato))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleProteinas)
                    .addComponent(resultadoProteina))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleGorduras)
                    .addComponent(resultadoGorduras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botaoVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        Recomendacao kcal = new Recomendacao();
        double carboidratos, proteinas, gordura;
        String carboidratoDiario, proteinaDiaria, gordurasDiaria;

        if (TxCaloriasDiarias.getText().isBlank() & TxCaloriasDiarias.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo precisa ser preenchido!\nExemplo:\nKcal: 2984.90 ou 2984");
        } else {
            try {

                kcal.setCalorias(Double.parseDouble(TxCaloriasDiarias.getText()));
                carboidratos = kcal.getCalorias() * 0.5 / 4;
                proteinas = kcal.getCalorias() * 0.25 / 4;
                gordura = kcal.getCalorias() * 0.25 / 9;

                if (kcal.getCalorias() == 0) {
                    throw new ArithmeticException("Informe um valor maior que ZERO!");
                }
                
                String strCarboidratos = String.format("%.2f g", carboidratos);
                String strProteinas = String.format("%.2f g", proteinas);
                String strGordura = String.format("%.2f g", gordura);

                resultadoCarboidrato.setText(strCarboidratos);
                resultadoProteina.setText(strProteinas);
                resultadoGorduras.setText(strGordura);

            } catch (ArithmeticException e) {
                JOptionPane.showMessageDialog(null, "Informe um valor maior que ZERO!", "ATENÇÃO", 2);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Valor inválido, apenas números!", "ATENÇÃO", 2);
            }

        }
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void TxCaloriasDiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCaloriasDiariasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCaloriasDiariasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRecomendacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxCaloriasDiarias;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel resultadoCarboidrato;
    private javax.swing.JLabel resultadoGorduras;
    private javax.swing.JLabel resultadoProteina;
    private javax.swing.JLabel titleCarboidratos;
    private javax.swing.JLabel titleGorduras;
    private javax.swing.JLabel titleProteinas;
    // End of variables declaration//GEN-END:variables
}
