/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastrofilme;

import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class TelaCadastroFilme extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFilme
     */
    public TelaCadastroFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelNomeFilme = new javax.swing.JLabel();
        txtFieldNomeFilme = new javax.swing.JTextField();
        labelDuracao = new javax.swing.JLabel();
        txtFieldDuracao = new javax.swing.JTextField();
        labelAno = new javax.swing.JLabel();
        txtFieldAno = new javax.swing.JTextField();
        labelDiretor = new javax.swing.JLabel();
        txtFieldDiretor = new javax.swing.JTextField();
        labelPais = new javax.swing.JLabel();
        txtFieldPais = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        comboBoxGenero = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        labelTitulo.setText("CADASTRO DE FILMES");

        labelNomeFilme.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelNomeFilme.setText("Nome do Filme:");

        txtFieldNomeFilme.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFieldNomeFilme.setToolTipText("Digite um nome para o filme neste campo");
        txtFieldNomeFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNomeFilmeActionPerformed(evt);
            }
        });

        labelDuracao.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelDuracao.setText("Duração:");

        txtFieldDuracao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFieldDuracao.setToolTipText("Digite a duração do filme neste campo");

        labelAno.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelAno.setText("Ano de Lançamento:");

        txtFieldAno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFieldAno.setToolTipText("Digite o ano de lançamento do filme neste campo");

        labelDiretor.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelDiretor.setText("Diretor:");

        txtFieldDiretor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFieldDiretor.setToolTipText("Digite um nome do diretor neste campo");

        labelPais.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelPais.setText("País de Lançamento:");

        txtFieldPais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFieldPais.setToolTipText("Digite o país de lançamento do filme neste campo");

        labelGenero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelGenero.setText("Gênero:");

        comboBoxGenero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um gênero:", "Ação", "Aventura", "Suspense", "Terror", "Ficção Científica", "Comédia", "Drama", "Fantasia", "Romance", "Documentário" }));
        comboBoxGenero.setToolTipText("Selecione o gênero do filme neste campo");

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton1.setText("CADASTRAR!");
        jButton1.setToolTipText("Clique para cadastrar o filme");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(labelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeFilme)
                            .addComponent(txtFieldNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDiretor)
                            .addComponent(txtFieldDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelGenero))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDuracao)
                            .addComponent(txtFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAno)
                            .addComponent(txtFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFieldPais)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeFilme)
                    .addComponent(labelDiretor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDuracao)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAno)
                        .addComponent(labelPais)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        txtFieldNomeFilme.getAccessibleContext().setAccessibleName("Campo de Texto");
        txtFieldNomeFilme.getAccessibleContext().setAccessibleDescription("Digite aqui o nome do filme");
        txtFieldNomeFilme.getAccessibleContext().setAccessibleParent(labelNomeFilme);
        txtFieldDiretor.getAccessibleContext().setAccessibleParent(labelDiretor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Filme f = new Filme();
        
        try {
            
            f.setNome(txtFieldNomeFilme.getText());
            
            f.setAnoLancamento(Integer.parseInt(txtFieldAno.getText()));
            
            f.setDuracao(Integer.parseInt(txtFieldDuracao.getText()));
            
            f.setDiretor(txtFieldDiretor.getText());
            
            f.setPaisLancamento(txtFieldPais.getText());
            
            f.setGenero(comboBoxGenero.getSelectedItem().toString());
            
            if(FilmeCSV.AdicionarFilme(f)) {
                JOptionPane.showMessageDialog(null, "Filme Cadastrado com Sucesso!\nOs dados cadastrados são:\nNome: " + f.getNome() 
                        + "\n" + "Diretor: " + f.getDiretor() + "\n" + "Ano de Lançamento: " + f.getAnoLancamento() +
                        "\n" + "País de Lançamento: " + f.getPaisLancamento() + "\n" + "Duração: " + f.getDuracao()+ 
                        "\n" + "Gênero: " + f.getGenero());
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Filme não pode ser cadastrado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFieldNomeFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNomeFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNomeFilmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxGenero;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelDiretor;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNomeFilme;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txtFieldAno;
    private javax.swing.JTextField txtFieldDiretor;
    private javax.swing.JTextField txtFieldDuracao;
    private javax.swing.JTextField txtFieldNomeFilme;
    private javax.swing.JTextField txtFieldPais;
    // End of variables declaration//GEN-END:variables
}
